name: Run Karate Tests

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean test

    - name: Run Karate Tests
      run: mvn test clean

    - name: List target directory contents
      run: ls ///home/runner/work/demotesting/demotesting/target/

    - name: Upload Karate Summary Reports
      uses: actions/upload-artifact@v3
      with:
        name: karate-reports
        path: target/cucumber-html-reports/**  # Adjust to your report path
