name: Run Karate Tests

on:
  workflow_dispatch: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build/Run Karate Tests
      run: mvn test -Dkarate.env=dev "-Dkarate.options=--tags @smoke"
      env:
          API_DEV: ${{ secrets.API_DEV }}

    - name: Upload Karate Summary Reports
      uses: actions/upload-artifact@v4
      with:
        name: karate-reports
        path: target/karate-reports/** 

    - name: Create index.html for Redirect
      run: |
        echo '<!DOCTYPE html>' > target/karate-reports/index.html
        echo '<html lang="en">' >> target/karate-reports/index.html
        echo '<head>' >> target/karate-reports/index.html
        echo '    <meta charset="UTF-8">' >> target/karate-reports/index.html
        echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> target/karate-reports/index.html
        echo '    <title>Redirecting...</title>' >> target/karate-reports/index.html
        echo '    <meta http-equiv="refresh" content="0; url=karate-summary.html">' >> target/karate-reports/index.html
        echo '</head>' >> target/karate-reports/index.html
        echo '<body>' >> target/karate-reports/index.html
        echo '    <p>If you are not redirected automatically, follow the <a href="karate-summary.html">link to the summary</a>.</p>' >> target/karate-reports/index.html
        echo '</body>' >> target/karate-reports/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/karate-reports
          publish_branch: gh-pages-v2
        
