name: Run Karate Tests

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build/Run Karate Tests
      run: mvn test

    - name: List target directory contents [BEFORE]
      run: ls

    - name: Upload Karate Summary Reports
      uses: actions/upload-artifact@v4
      with:
        name: karate-reports
        path: target/karate-reports/** 

    - name: List target directory contents [AFTER]
      run: ls

